include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_declarations: true
    always_specify_types: false
    avoid_void_async: true
    prefer_final_fields: true
    use_key_in_widget_constructors: true
