name: papantulis_chat
description: Aplikasi Papan Tulis Chat dan Mading Estetik menggunakan Flutter & Firebase.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- UTAMA: FIREBASE ---
  firebase_core: ^3.0.0
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.7.0
  firebase_storage: ^12.4.10

  # --- IKON & UTILITAS ---
  cupertino_icons: ^1.0.6
  image_picker: ^1.1.2
  file_picker: ^8.3.2
  url_launcher: ^6.3.1

  # --- PANGGILAN: WEBRTC & LIVEKIT (PENGGANTI ZEGO) ---
  flutter_webrtc: ^0.12.12
  livekit_client: ^2.0.0

  # --- UTENSIL VOICE NOTE & AUDIO PLAYER ---
  record: ^5.2.1
  audioplayers: ^6.0.0
  http: ^1.2.0

  # --- TAMBAHAN UNTUK WIFI STATUS ---
  connectivity_plus: ^6.1.5
  network_info_plus: ^6.1.0

  # --- TAMBAHAN UNTUK CHAT LOCK (BARU) ---
  shared_preferences: ^2.2.2

  # --- izin kamera dan mikrofone ---
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # Alat pembuat logo otomatis
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  # Gambar logo kamu didaftarkan di sini
  assets:
    - assets/icons/logo.png

# Pengaturan letak logo kamu
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

dependency_overrides:
  record_platform_interface: ^1.2.2
