buildscript {
    // Diubah ke 1.9.22 untuk stabilitas maksimal dengan Flutter SDK terbaru
    ext.kotlin_version = '2.0.0'
    
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // Plugin Kompiler Kotlin
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        
        // Plugin Google Services wajib untuk Firebase
        classpath 'com.google.gms:google-services:4.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}