name: Build APK Otomatis

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode dari Repo
      uses: actions/checkout@v4

    - name: Pasang Java (JDK)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Pasang Flutter Versi Kompatibel
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'
        channel: 'stable'

    - name: Ambil Package Flutter
      run: flutter pub get

    - name: Bersihkan Cache Lama
      run: flutter clean

    - name: Rakit Jadi APK Release
      run: flutter build apk --release --performance --gradle-org.gradle.jvmargs="-Xmx2500m -XX:MaxMetaspaceSize=512m"

    - name: Simpan File APK
      uses: actions/upload-artifact@v4
      with:
        name: aplikasi-cetan-apk
        path: build/app/outputs/flutter-apk/app-release.apk
